### ISSUE TITLE
Idea similar to yours

### ISSUE THREAD

**Issue by Sim4n6** [ivan-sincek/penetration-testing-cheat-sheet#1]
Hello, 

I am working on something similar to what you are doing here :) different concept but similar some how. My idea is from within the terminal you can grab two or three possible documented commands of pentesting. For instance:  `curl pnt.sh/nmap`

Please feel free to check this out. https://github.com/Sim4n6/pntsh

**Comment by ivan-sincek** [comment]
Hi,

Thanks for the info. I will make sure to check your tool and mention it in the next update if I find it useful. Keep the good work!

Best regards,
Ivan.
